HalvaWebApplication/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HalvaWebApplication.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

HalvaWebApplication/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HalvaWebApplication.Code.Interfaces;
using HalvaWebApplication.Code.DataObjects;
using HalvaWebApplication.Code.Repositories;
using HalvaWebApplication.Code.Extension_Methods;

namespace HalvaWebApplication.Controllers
{
    public class BlogController : Controller
    {
		public BlogController(IDataEntityRepository<BlogPost> dataInterface)
		{
			m_repository = dataInterface;
		}

        public ActionResult Index()
        {
			List<BlogPost> blogs = m_repository.GetList();
			return View(blogs);
        }

		[HttpPost]
		public ActionResult Index(string Filter)
		{
			List<BlogPost> blogs = m_repository.GetListByContent(Filter);
			return View(blogs);
		}

		public ActionResult Show(int ID)
		{
			BlogPost post = m_repository.Get(ID);

			if (post != null)
				return View(post);
			else
				return View();
		}

		[Authorize]
		public ActionResult Add()
		{
			Models.BlogPostModel blog = new Models.BlogPostModel();

			return View(blog);
		}

		[HttpPost]
		public ActionResult Add(Models.BlogPostModel model)
		{
			if (ModelState.IsValid)
			{
				BlogPost post = new BlogPost();
				post.ID = model.ID;
				post.Author = model.Author;
				post.Title = model.Title;
				post.Content = model.Content;

				m_repository.Save(post);
			}
			else
				return View(model);

			return RedirectToAction("Index");
		}

		[Authorize]
		public ActionResult Edit(int id)
		{
			BlogPost blog = m_repository.Get(id);
			Models.BlogPostModel model = new Models.BlogPostModel();
			model.ID = blog.ID;
			model.Author = blog.Author;
			model.Title = blog.Title;
			model.Content = blog.Content;

			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(Models.BlogPostModel model)
		{
			if (ModelState.IsValid)
			{
				BlogPost post = new BlogPost();
				post.ID = model.ID;
				post.Author = model.Author;
				post.Title = model.Title;
				post.Content = model.Content;

				m_repository.Save(post);
			}
			else
				return View(model);

			return RedirectToAction("Index");
		}

		private IDataEntityRepository<BlogPost> m_repository;

    }
}

HalvaWebApplication/Controllers/GameItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HalvaWebApplication.Code.Interfaces;
using HalvaWebApplication.Code.DataObjects;
using HalvaWebApplication.Models.GameItem;
using HalvaWebApplication.Code.Repositories;

namespace HalvaWebApplication.Controllers
{
    public class GameItemController : Controller
    {
		public GameItemController(IDataEntityRepository<GameItem> ItemInterface, IDataEntityRepository<GameItemCategory> CategoryInterface)
		{
			m_repository = ItemInterface;
			m_categoryRepository = CategoryInterface;
		}

        // GET: GameItem
        public ActionResult Index()
        {
			List<GameItem> items = m_repository.GetList();
			List<GameItemModel> models = new List<GameItemModel>();

			List<SelectListItem> categories = constructCategoryList();

			foreach(GameItem item in items)
			{
				GameItemModel newItem = new GameItemModel(item);
				newItem.CategoryList = categories;
				models.Add(newItem);
			}

            return View(models);
        }

		[HttpPost]
		public ActionResult Index(string NameFilter, string CategoryFilter)
		{
			//TODO: Make this filter at the SQL server and not here.
			List<GameItem> items = m_repository.GetList();

			List<GameItem> filteredItems = null;

			int categoryFilterID = Int32.Parse(CategoryFilter);

			if (categoryFilterID != -1)
			{
				filteredItems = items.Where(m => m.ItemCategoryID == categoryFilterID).ToList();
			}
			else
			{
				filteredItems = items;
			}

			filteredItems = filteredItems.Where(m => m.ItemName.Contains(NameFilter)).ToList();

			List<GameItemModel> modelList = new List<GameItemModel>();
			List<SelectListItem> categories = constructCategoryList();

			foreach (GameItem item in filteredItems)
			{
				GameItemModel newItem = new GameItemModel(item);
				newItem.CategoryList = categories;
				modelList.Add(newItem);
			}

			return View(modelList);
		}

		public ActionResult Display(int ID)
		{
			GameItemModel model = new GameItemModel(m_repository.Get(ID));
			model.CategoryList = constructCategoryList();

			return View(model);
		}

		public ActionResult Add()
		{
			GameItemModel model = new GameItemModel();
			model.CategoryList = constructCategoryList();

			return View(model);
		}

		[HttpPost]
		public ActionResult Add(GameItemModel Model)
		{
			if (ModelState.IsValid)
			{
				GameItem item = new GameItem();
				item.ID = Model.ID;
				item.ItemCode = Model.ItemCode;
				item.ItemName = Model.ItemName;
				item.ItemCategoryID = Model.ItemCategoryID;
				item.ItemDescription = Model.ItemDescription;
				item.ItemAttributeID = 1;
				item.ItemAttributeQuantity = Model.ItemAttributeQuantity;
				item.ItemImage = item.ItemImage;
				item.ItemPrice = item.ItemPrice;

				m_repository.Save(item);
			}
			else
				return View(Model);

			return RedirectToAction("Index");
		}

		public ActionResult Edit(int ID)
		{
			GameItem item = m_repository.Get(ID);

			GameItemModel model = new GameItemModel();

			if (item != null)
			{
				model.ID = item.ID;
				model.ItemCode = item.ItemCode;
				model.ItemName = item.ItemName;
				model.ItemCategoryID = item.ItemCategoryID;
				model.ItemDescription = item.ItemDescription;
				model.ItemAttributeID = 1;
				model.ItemAttributeQuantity = item.ItemAttributeQuantity;
				model.ItemImage = item.ItemImage;
				model.ItemPrice = item.ItemPrice;
				model.CategoryList = constructCategoryList();
			}
			else
				return RedirectToAction("Index");

			return View(model);
		}

		[HttpPost]
		public ActionResult Edit(GameItemModel Model)
		{
			if (ModelState.IsValid)
			{
				GameItem item = new GameItem();
				item.ID = Model.ID;
				item.ItemCode = Model.ItemCode;
				item.ItemName = Model.ItemName;
				item.ItemCategoryID = Model.ItemCategoryID;
				item.ItemDescription = Model.ItemDescription;
				item.ItemAttributeID = 1;
				item.ItemAttributeQuantity = Model.ItemAttributeQuantity;
				item.ItemImage = Model.ItemImage;
				item.ItemPrice = Model.ItemPrice;
			}
			else
				return View(Model);

			return RedirectToAction("Index");
		}


		public ActionResult Delete(int ID)
		{
			m_repository.Delete(ID);

			return RedirectToAction("Index");
		}

		private List<SelectListItem> constructCategoryList()
		{
			List<SelectListItem> categoryList = new List<SelectListItem>();
			m_categoryRepository.GetList().ForEach(listItem => categoryList.Add(new SelectListItem() { Text = listItem.CategoryName, Value = listItem.ID.ToString() }));

			return categoryList;
		}


		private IDataEntityRepository<GameItem> m_repository;
		private IDataEntityRepository<GameItemCategory> m_categoryRepository;
    }
}

HalvaWebApplication/Views/Shared/_BlogPostLinkList.cshtml
@model IEnumerable<HalvaWebApplication.Code.DataObjects.BlogPost>

@foreach(HalvaWebApplication.Code.DataObjects.BlogPost post in Model)
{
    <div class="uxBlogPostSummary">
        @Html.ActionLink(post.Title, "Show", "Blog", post, null)
        <time>@post.Timestamp</time>
        @if (User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("Edit", "Edit", "Blog", post, null)
        }
    </div>
}

HalvaWebApplication/Views/Shared/_GameItemModelLinkList.cshtml
@using HalvaWebApplication.Models.GameItem;
@model IEnumerable<GameItemModel>

@foreach (GameItemModel item in Model)
{
    <div class="uxGameItemSumary">

        @Html.ActionLink(item.ItemName, "Display", "GameItem", item, null)

        @if (User.Identity.IsAuthenticated)
        {
            @Html.ActionLink("Edit", "Edit", "GameItem", item, null)
             
            @Html.ActionLink("Delete", "Delete", "GameItem", item, null)
        }

    </div>
}

HalvaWebApplication/Views/Shared/_Layout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" type="text/css" href="~/CSS/HalvaDefaultStyle.css"/>
	@RenderSection("styles", false)
</head>
<body>
	<div> 
		<div id="uxBanner">
			<div id="uxLogo">
				<img src="~/Resources/WheatSheaf.svg" alt="Bundle of wheat"/>
			</div>
			<div id="uxBannerText">
				<div id="uxSiteName">Halva</div>
				<div id="uxSlogan">Be a gluten for punishment.</div>
				<div id="uxLogin">
					@if(User.Identity.IsAuthenticated)
                    {
                        <div>Welcome, @User.Identity.Name</div>
                        using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new { @id = "logoutForm"}))
                        {
                            @Html.AntiForgeryToken()
                            <a href="Logout" onclick="document.getElementById('logoutForm').submit(); return false;">Logout</a>
                        }
                    }
                    else
                    {
                        @Html.ActionLink("Login", "Login", "Account");
                    }
				</div>
			</div>
			<div style="clear:both"></div>
		</div>
		<header>
            <div id="uxNavigation">
                @RenderSection("navigation", false)
            </div>
		</header>
        <div id="uxMainBody">
		    @RenderBody()
        </div>
		@RenderSection("footer", false)
	</div>

	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.js"></script>

</body>
</html>

HalvaWebApplication/Views/Shared/_NavigationLinks.cshtml
@Html.ActionLink("Home", "Index", "Home", null, null)
@Html.ActionLink("Blog", "Index", "Blog", null, null)
@Html.ActionLink("Items", "Index", "GameItem", null, null)
@Html.ActionLink("Contact", "Index", "Contact", null, null)
@Html.ActionLink("About us", "Index", "About", null, null)